apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: account-microservice
  template:
    metadata:
      labels:
        app: account-microservice
    spec:
      containers:
        - name: account-microservice
          image: cyberspetzdocker/account-microservice:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/mydatabase
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: SPRING_ZIPKIN_BASE_URL
              value: "http://zipkin:9411/"
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              value: "http://zipkin:9411/api/v2/spans"
            - name: MANAGEMENT_TRACING_SAMPLING_PROBABILITY
              value: "1.0"
            - name: MANAGEMENT_TRACING_ENABLED
              value: "true"
            - name: LOGGING_LEVEL_IO_MICROMETER_TRACING
              value: "DEBUG"


          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi