apiVersion: apps/v1
kind: Deployment
metadata:
  name: idv-microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: idv-microservice
  template:
    metadata:
      labels:
        app: idv-microservice
    spec:
      containers:
        - name: idv-microservice
          image: cyberspetzdocker/idv-microservice:latest
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/mydatabase
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
