apiVersion: v1
kind: Service
metadata:
  name: springboot-service
spec:
  selector:
    app: springboot-app
  ports:
    - protocol: TCP
      port: 80        # Cluster port
      targetPort: 8080 # App container port
  type: ClusterIP
